### ISSUE TITLE
Expression in a class literal has a nullable type 'Note?', use !! to make the type non-nullable

### ISSUE THREAD

**Issue by sergefonville** [probelalkhan/my-notes-app#2]
At https://youtu.be/MbPogh-pdHM?list=PLk7v1Z2rk4hg_ywZffPgRTmJoy2XWs02d&t=213 the rebuild step fails for me with the error in both `AddNoteFragmentArgs.kt` and `HomeFragmentDirections.kt`:
`Expression in a class literal has a nullable type 'Note?', use !! to make the type non-nullable`
How do I resolve this so I can continue the tutorial?

It seems to me that the class is incorrectly generated, the `Note` type is not nullable and the type passed between the actions is.

**Comment by sergefonville** [comment]
I noticed that when I clone and build this project, the problem-files are `.java` instead of `.kt` in mine

**Comment by sergefonville** [comment]
The issue was that I had `apply plugin: "androidx.navigation.safeargs.kotlin"` in my app's build.gradle instead of `apply plugin: "androidx.navigation.safeargs"`, so it seems that the kotlin version does not produce correct code.

**Comment by sergefonville** [comment]
The real problem was that the argument had `android:name="Note"` which is also the name of the class, this causes confusion for the compiler where the name of the variable and the class is the same, this was solved by changing it to `android:name="note"` (lowercase), then it compiles correctly with `apply plugin: "androidx.navigation.safeargs.kotlin"`. This issues does not exist in java, since it does not have nullable types like kotlin does.

**Comment by Limatucano** [comment]
thank you so much @sergefonville, I was unable to resolve this error in my project
